#!/bin/sh
# Copyright (C) 2015 Glen Pitt-Pladdy
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# See: https://www.pitt-pladdy.com/blog/_20150108-225908_0000_php-fpm_on_Cacti_via_SNMP/

STATUSURL=http://localhost/status


data=`curl --silent $STATUSURL`

dataline() {
	echo "$data" | grep "^$1:" | sed "s/^$1: *//"
}

dataline 'accepted conn'
dataline 'listen queue'
dataline 'max listen queue'
dataline 'listen queue len'
dataline 'idle processes'
dataline 'active processes'
dataline 'total processes'
dataline 'max active processes'
dataline 'max children reached'
dataline 'slow requests'

